// Code generated by MockGen. DO NOT EDIT.
// Source: lbc-fizzbuzz/internal/services (interfaces: IFizzBuzzService)

// Package mock_services is a generated GoMock package.
package mock_services

import (
	models "lbc-fizzbuzz/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIFizzBuzzService is a mock of IFizzBuzzService interface.
type MockIFizzBuzzService struct {
	ctrl     *gomock.Controller
	recorder *MockIFizzBuzzServiceMockRecorder
}

// MockIFizzBuzzServiceMockRecorder is the mock recorder for MockIFizzBuzzService.
type MockIFizzBuzzServiceMockRecorder struct {
	mock *MockIFizzBuzzService
}

// NewMockIFizzBuzzService creates a new mock instance.
func NewMockIFizzBuzzService(ctrl *gomock.Controller) *MockIFizzBuzzService {
	mock := &MockIFizzBuzzService{ctrl: ctrl}
	mock.recorder = &MockIFizzBuzzServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFizzBuzzService) EXPECT() *MockIFizzBuzzServiceMockRecorder {
	return m.recorder
}

// DoFizzBuzz mocks base method.
func (m *MockIFizzBuzzService) DoFizzBuzz(arg0 *models.FizzBuzz) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoFizzBuzz", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// DoFizzBuzz indicates an expected call of DoFizzBuzz.
func (mr *MockIFizzBuzzServiceMockRecorder) DoFizzBuzz(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoFizzBuzz", reflect.TypeOf((*MockIFizzBuzzService)(nil).DoFizzBuzz), arg0)
}
